[build]
  command = "VITE_SUPABASE_URL=$VITE_SUPABASE_URL VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_ANON_KEY = ""
  VITE_SUPABASE_URL = ""
  VITE_OPENAI_API_KEY = ""

[[plugins]]
  package = "@netlify/plugin-ignore-build-step"
